config/routes.rb
IitMarketplace::Application.routes.draw do

  root :to => 'application#home'
  resources :adverts
  resources :reverseadverts 
  resources :users do
    resources :intervals
    member do
      post 'change_password'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :intervals
  resources :payments

  match '/pay', to: 'payments#create'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match '/sendemail', to: 'users#send_simple_message', via: :post
  match '/sendpass', to: 'users#send_password', via: :post

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  name            :string(255)
#  password_digest :string(255)
#  remember_token  :string(255)
#

class User < ActiveRecord::Base

  has_many :Advert
  has_many :Interval

  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
            format:     { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if(params[:q]!="#{ :email[0].ord}#{ :email[1].ord}#{ :email[2].ord}#{ :email[3].ord}#{ :email[4].ord}")
      flash[:error]="Wrong confirmation code"
      render 'new'
    else
        if(params[:user][:email][/iit.edu/])
          if @user.save
            
            sign_in @user
            flash[:success] = "Welcome to IIT Marketplace"
            redirect_to @user
          else
            render 'new'
          end
        else
          flash[:error]="Not a iit.edu e-mail"
          render 'new'
        end
  
  end
    
  end

  def edit
    @user = User.find(params[:id])
  end

  def change_password
    @user = User.find(params[:id])
    if @user.authenticate(params[:current_password]) && params[:new_password]==params[:new_password_confirmation]
      @user.password= params[:new_password]
      @user.password_confirmation= params[:new_password_confirmation]
      @user.save
      flash[:success]="Password changed"
      redirect_to user_path
    else
      flash[:error]="Passwords don't match"
      redirect_to edit_user_path
    end
  end

  def send_simple_message
    RestClient.post "https://api:key-90u-14v55im4kblo8ystnkcat9irhre4"\
    "@api.mailgun.net/v2/iitmarketplace.mailgun.org/messages",
    :from => "iitmarketplace@iitmarketplace.mailgun.org",
    :to => params[:email],
    :subject => "Confirmation Code",
    :text => "Welcome to the IIT Marketplace!\nYou confirmation code is: #{ :email[0].ord}#{ :email[1].ord}#{ :email[2].ord}#{ :email[3].ord}#{ :email[4].ord}"

  end
  def send_password
    RestClient.post "https://api:key-90u-14v55im4kblo8ystnkcat9irhre4"\
    "@api.mailgun.net/v2/iitmarketplace.mailgun.org/messages",
    :from => "iitmarketplace@iitmarketplace.mailgun.org",
    :to => params[:email],
    :subject => "Forgotten Password",
    :text => "Your new password is: #{new_password}"

  end
  def new_password
    chars = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
    newpass = ""
    1.upto(8) { |i| newpass << chars[rand(chars.size-1)] }
    @user=User.where("email = ?", params[:email]).first
    @user.password = newpass
    @user.password_confirmation = newpass
    @user.save
    return newpass
    
  end

end

app/helpers/users_helper.rb
module UsersHelper
	
end

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.submit "Change name", class: "btn btn-large btn-primary" %>
     <% end %>

     <%= form_tag(change_password_user_path(@user), :method =>"post") do %>

        <%= label_tag :current_password, "Current password" %>
        <%= password_field_tag :current_password %>

        <%= label_tag :new_password, "New password" %>
        <%= password_field_tag :new_password %>

        <%= label_tag :new_password_confirmation, "New password confirmation" %>
        <%= password_field_tag :new_password_confirmation %>

        <%= submit_tag "Change password", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>

        <%= render 'shared/error_messages' %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= label_tag(:q, "Enter confirmation code") %>
        <%= text_field_tag(:q) %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Password Confirmation" %>
        <%= f.password_field :password_confirmation %>

        <br/><br/>

        <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
        <button class="btn btn-large btn-primary" style="float:right;" onclick='askforemail()'>Send confirmation code</button>
    <% end %>

  </div>
</div>
<script type="text/javascript">

function askforemail()
{
   
    var emailaddress=document.getElementById('user_email').value;
    if(emailaddress.indexOf( "iit.edu" ) > -1 )
    {
        $.post('/sendemail',{email:emailaddress},'');
    }
    else
    {
        alert("Not an iit.edu e-mail");
    }
}   
</script>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
    <h1 text-align: center>Welcome to the IIT Marketplace!</h1>
  </div>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= @user.name %> <%= link_to "Edit profile", edit_user_path(@user)%>
      </h1>
      </section>
      <section>
      <h2>
        <%= @user.email %>
      </h2>
    </section>
  </aside>
</div>

<%= link_to "Available Delivery Times", user_intervals_path(@user)%>
