config/routes.rb
IitMarketplace::Application.routes.draw do

  root :to => 'application#home'
  resources :adverts
  resources :reverseadverts 
  resources :users do
    resources :intervals
    member do
      post 'change_password'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :intervals
  resources :payments

  match '/pay', to: 'payments#create'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match '/sendemail', to: 'users#send_simple_message', via: :post
  match '/sendpass', to: 'users#send_password', via: :post

end

app/models/advert.rb
# == Schema Information
#
# Table name: adverts
#
#  id              :integer          not null, primary key
#  title           :string(255)
#  description     :text
#  reverse         :boolean
#  price           :float
#  expiration_date :datetime
#  user_id         :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Advert < ActiveRecord::Base

  belongs_to :user
  has_attached_file :advertphoto, styles: {medium: "486x365>"},
  url: "/assets/adverts/:id/:style/:basename.:extension",
  path: ":rails_root/public/assets/adverts/:id/:style/:basename.:extension"

  validates_attachment_size :advertphoto, less_than: 7.megabytes
  validates_attachment_content_type :advertphoto, content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']

  validates :title, presence: true
  validates :description, presence: true, length:{minimum: 10}
  validates :price, presence: true
end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
	
	def new 
		@advert = Advert.new
	end

	def create
	  	if !signed_in?
			flash[:error] = "You need to login first!!!"
			redirect_to root_path
		else
	  		@advert = Advert.new(params[:advert])
			@advert.user_id = current_user.id
			@advert.save
			flash[:success] = "You just created a new Add!!!"
			redirect_to new_interval_path
      	end
	end

	def index
		@adverts = Advert.where("reverse = ?",false)
		@reverseadverts=Advert.where("reverse = ?",true)
	end

	def show
		@advert = Advert.find(params[:id])
		@user = User.find(@advert.user_id)
	end
 
    def edit
	  	@advert = Advert.find(params[:id])
    	if !(signed_in? && correct_user?)
			flash[:error] = "You don't have the permission to edit it!!!"
			redirect_to root_path
      	end
    end

	def update
		@advert = Advert.find(params[:id])
		if !(signed_in? && correct_user?)
			flash[:error] = "You don't have the permission to delete it!!!"
		   redirect_to adverts_path
		else
		    @advert.update_attributes(params[:advert])
		    flash[:success] = "You just updated the Add!!!"
			redirect_to advert_path
		end
	end

	def destroy
		@advert = Advert.find(params[:id])
	    if !(signed_in? && correct_user?)
	       flash[:error] = "You don't have the permission to delete it!!!"
		   redirect_to adverts_path
	    else
		   @advert.destroy
		   flash[:success] = "You have just delete the Advert"
		   redirect_to adverts_path
	    end
	end

    
end

app/helpers/adverts_helper.rb
module AdvertsHelper

	def correct_user?
    		return @advert.user_id.to_i == current_user.id
    	end


end

app/views/adverts/edit.html.erb
<% provide(:title, "Edit") %>

<h1>Edit your Advertisement</h1><br/><br/>
<a class="btn" href="/adverts/<%= "#{@advert.id}"%>"><i class=" icon-circle-arrow-left"></i></a><b> Back to the ad</b><br/><br/>

<%= form_for @advert, html: {multipart: true} do |f| %>

<div class="field">
  <%= f.label :title, "Title" %><br/>
  <%= f.text_field :title %><br/><br/><br/>
</div>

<div class="field">
    <%= f.label :description, "Description" %><br/>
    <%= f.text_area :description %><br/><br/><br/>
  </div>

  <div class="field">
    <%= f.label :price, "Price (USD):"%><br/>
    <%= f.text_field :price%><br/><br/><br/><br/>
  </div>

  <div class="field">
    <%= f.label :advertphoto, "Add photo to your ad"%>
    <%= f.file_field :advertphoto%><br/><br/><br/>
  </div>

  <div class="action">
    <%= f.submit "Submit !", class: "btn btn-success"%>
  </div>

<% end %>

app/views/adverts/index.html.erb
<% provide(:title, "Ads") %>
<h1>Adverts</h1>

Stuff people are selling:
<ul>
  <% @adverts.each do |ad| %>
      <li>
        <%= link_to ad.title, ad%>
      </li>
  <% end %>
</ul>


<%= link_to "New ad", new_advert_path%><br/><br/><br/><br/>


Stuff people are looking for:
<ul>
  <% @reverseadverts.each do |ad| %>
      <li>
        <%= link_to ad.title, ad%>
      </li>
  <% end %>
</ul>

<%= link_to "New ad", new_advert_path%><br/><br/><br/><br/>

<%= debug(params) if Rails.env.development? %>

app/views/adverts/new.html.erb
<h1>New add</h1>

<a class="btn" href="/adverts/"><i class=" icon-circle-arrow-left"></i></a><b> Give up? Go back</b><br/><br/><br/>

<%= form_for @advert, html: {multipart: true} do |f| %>

<% if @advert.errors.any?%>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(@advert.errors.count, "error") %>.
      </div>
      <ul>
        <% @advert.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<div class="field">
  <b>Tick this if you want this to be a reverse advert</b>
  <%=f.check_box :reverse%><br/><br/><br/>
</div>

  <div class="field">
    <%= f.label :title, "Title" %><br />
    <%= f.text_field :title %><br/><br/><br/>
  </div>

  <div class="field">
    <%= f.label :description, "Description" %><br/>
    <%= f.text_area :description %><br/><br/><br/>
  </div>

  <div class="field">
    <%= f.label :price, "Price (USD):"%><br/>
    <%= f.text_field :price%><br/><br/><br/>
  </div>

  <div class="field">
    <%= f.label :advertphoto, "Add photo to your ad"%>
    <%= f.file_field :advertphoto%><br/><br/><br/>
  </div>

  <div class="action">
    <%= f.submit "Continue", class: "btn btn-success" %>
  </div>
<% end %> 

app/views/adverts/show.html.erb
<% provide(:title, "#{@advert.title}") %>
<h1><%=@advert.title%></h1>


<p><%=@advert.description%></p>

<p><%= @advert.price %></p><br/><br/>

<%if @advert.advertphoto_file_name != nil%>
   <%= image_tag @advert.advertphoto.url(:medium)%><br/><br/><br/><br/>
<%end%>

<p>Price limit: $ 
<%= @advert.price %></p><br/><br/><br/>

<% if signed_in? && correct_user?%>
<%=link_to "Edit", edit_advert_path, class: "btn btn-inverse"%><br/>
<br>

<%= button_to "Delete", advert_path, method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure you want to delete this advert?"}%><br/>
<br>
<% end %>
<%=link_to "Back to ads list", adverts_path, class: "btn btn-primary"%><br/>