config/routes.rb
IitMarketplace::Application.routes.draw do

  root :to => 'application#home'
  resources :adverts
  resources :reverseadverts 
  resources :users do
    resources :intervals
    member do
      post 'change_password'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :intervals
  resources :payments

  match '/pay', to: 'payments#create'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match '/sendemail', to: 'users#send_simple_message', via: :post
  match '/sendpass', to: 'users#send_password', via: :post

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    by Léo Larrère & Victor Mours & Hristo Nenov & Yang Song
  </small>
  <nav>
    <ul>
      <li><a href="http://www.iit.edu/">IIT Website</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to image_tag("iit_logo.png", alt:"IIT Websites"), "http://www.iit.edu", id: "logo_image"%>
      <%= link_to "IIT Marketplace", root_path, id: "logo" %>
        <ul class="nav pull-right">
          <% if signed_in? %> 
            <li><%= link_to current_user.name, user_path(current_user.id)%></li>
          <% end %>
          <li><%= link_to image_tag("homepage_out.png", mouseover: "homepage_over.png",alt: "Homepage"), adverts_path %></li>
          <% if signed_in? %>
              <li><%= link_to image_tag("sign in_out.png", alt:"Sign in or Sign out"), signout_path, method: :delete %></li>
          <% else %>
              <li><%= link_to image_tag("sign in_out.png", alt:"Sign in or Sign out"), signin_path %></li>
          <% end %>
        </ul>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>